### ISSUE TITLE
consult with the code

### ISSUE THREAD

**Issue by JiaqianLi** [FunkyKoki/RetinexNet_PyTorch#2]
`
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from dataset import TheDataset
  File "/home/scw4750/LJQ/RetinexNet_PyTorch/dataset.py", line 51, in <module>
    class TheDataset(data.dataset):
TypeError: module() takes at most 2 arguments (3 given)
`
hello, thank you for share your code. When I run the train.py, I meet the error above and how can I solve it? 
Looking forward for your reply!

**Comment by spp123123** [comment]
hello， I meet the problem too, if you solve it ,please help me !
Looking forward for your reply!

**Comment by JiaqianLi** [comment]
hello, I am sorry that I do not solve the problem.

**Comment by spp123123** [comment]
It hasn't been solved, but thank you all the same

**Comment by Klawens** [comment]
Problem solved, use
from torch.utils.data.dataset import Dataset
class TheDataset(Dataset):
